name: CI Pull Requests
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Danger
        uses: docker://ghcr.io/danger/danger-js:11.2.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "--dangerfile dangerfile.js --id=default"
      - name: Danger-Foo
        uses: docker://ghcr.io/danger/danger-js:11.2.7
        with:
          args: "--dangerfile dangerfile-foo.js --id=foo"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
